ALTER TABLE usage_logs DROP COLUMN IF EXISTS team_id;
ALTER TABLE api_keys DROP COLUMN IF EXISTS team_id;
ALTER TABLE api_keys DROP COLUMN IF EXISTS created_by_id;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS users;
