// Package apidoc embeds the bundled OpenAPI spec so the gateway can serve it
// from the binary (single-binary, no runtime file dependency). The bundle is
// generated by `make spec-bundle` (cmd/merge-spec) from the modular source in
// docs/api/ and committed; CI runs `make spec-check` to fail if it drifts.
package apidoc

import _ "embed"

//go:embed openapi.bundled.json
var SpecJSON []byte
